In [18]:
import numpy as np
import pandas as pd
import random
import datetime

In [24]:
df = pd.read_csv('heart.csv')
df = df[['age','sex','trtbps','thalachh', 'restecg','output']]
df.columns = ['Age', 'Sex', 'Resting Blood Pressure', 'Maximum Heart Rate', 'Resting ECG', 'Output']
df['Is Emergency'] = (df['Output'] == 1)
df = df.drop(columns='Output')
df = df.sample(frac=1)
df

,Age,Sex,Resting Blood Pressure,Maximum Heart Rate,Resting ECG,Is Emergency
178,43,1,120,120,0,False
301,57,1,130,115,1,False
237,60,1,140,170,0,False
159,56,1,130,163,0,True
113,43,1,110,161,1,True
...,...,...,...,...,...,...
67,45,0,130,175,0,True
140,51,0,120,157,0,True
260,66,0,178,165,1,False
21,44,1,130,179,1,True
97,52,1,108,147,1,True

In [27]:
output_file = df.to_json('vitals_readings.json',  orient='records')
output_file